apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio
spec:
  type: NodePort
  ports:
  - name: "portfolio-service"
    port: 5173
    targetPort: 5000
    nodePort: 31005
  selector:
    app: portfolio
